const yaml = require('js-yaml');

let a = {name:"A"}; // update to person structure
let b = {name:"B"};
let c = {name:"C"}
let member = {a,b,c};

let inherit = {doc:"docurl",code:"codeurl"}; // update to contract
let trade = {doc:"docurl",code:"codeurl"}; // update to contract
let iteration = {inherit,trade};

let department = {doc:"docurl",code:"codeurl"}; // update to contract
let budget = {doc:"docurl",code:"codeurl"}; // update to contract
let election = {doc:"docurl",code:"codeurl"}; // update to contract
let legislation = {doc:"docurl",code:"codeurl"}; // update to contract
let baseright = {department,budget,election,legislation};

let unknown = {doc:"docurl",code:"codeurl"}; // update to contract : to solve the unknown problems.
let resource = {doc:"docurl",code:"codeurl"}; // update to contract : get resource by future promise.
let baseduty = {unknown,resource};

let dirctos = {}; //

kernel();

function kernel(){

  console.log("kernel member are:",member);
  console.log("new member generated by:",iteration);
  console.log("kernel exercise right to self:",baseright);
  console.log("kernel exercise right to:","director",baseright);
  console.log("kernel undertake duty to:","director",baseduty);
  console.log("the remaining of the third in the past Fiscal periods of:","dirctos", "is income of kernel.");// can't understand. maybe one third of remaining of dorector...
}